### ISSUE TITLE
Is it possible to get a raw uncompressed version of one of your images?

### ISSUE THREAD

**Issue by dogunbound** [Harshit-T/Wallpapers#1]
https://raw.githubusercontent.com/Harshit-T/Wallpapers/main/walls/game.jpg

I've noticed some compression going on in the photo. Wondering is you had a uncompressed copy.

**Comment by Harshit-T** [comment]
I'm sorry, but you'll just have to google the image and see if you can find an uncompressed one

**Comment by Harshit-T** [comment]
Here's the link to the original artist : [https://twitter.com/jmw327?t=JxierzGUZ53F-4rslUl9iA&s=09](https://twitter.com/jmw327?t=JxierzGUZ53F-4rslUl9iA&s=09)
